[package]
name = "crabfish"
version = "0.1.0"
authors = ["Jonathan Li <30177086+MonliH@users.noreply.github.com>"]
edition = "2018"

[dependencies]
chess = "3"
smallvec = "1"
clap = "3.0.0-beta.2"
rustc-hash = "1.1.0"
crossbeam = "0.8.0"

[profile.release]
lto = "fat"
